### ISSUE TITLE
Login email went to junk

### ISSUE THREAD

**Issue by nycdotnet** [VestU/login#1]
Hi,
The login email went to junk.  Have you seen this?

http://blog.codinghorror.com/so-youd-like-to-send-some-email-through-code/

**Comment by diverted247** [comment]
Enabled DKIM address validation for all sender addresses on vestu.com. The DKIM was disabled for admin@vestu.com so that is one potential issue regarding marked as junk.

Thanks!

**Comment by diverted247** [comment]
Also going through the Port25 test on system... Send email to check-auth@verifier.port25.com and receive report

**Comment by nycdotnet** [comment]
Tried again with a different email address (Google) and it arrived fine and the process seemed to work correctly.  I haven't tried again with my Outlook account since I figure I've poisoned the well by clicking "not spam" on it.

**Comment by diverted247** [comment]
Seeing same results on all my accounts. Thanks for testing I will upgrade your account to Lifetime!
